In [ ]:
import numpy as np
from scipy.linalg import solve_continuous_are

In [ ]:
# Task 4.1: Checking Controllability and Observability

A = np.array([[0, 1, 0], [0, 1, 1], [1, 2, 3]])
B = np.array([[1], [0], [0]])
C = np.array([[1, 0, 1]])
D = np.array([[1]])

In [ ]:
# Compute the observability matrix

A = np.array([[0, 1, 0], [0, 1, 1], [1, 2, 3]])
C = np.array([[1, 0, 1]])

# Compute the observability matrix
Obsv = np.vstack([C, C @ A, C @ A @ A])

# Compute the rank
rank_O = np.linalg.matrix_rank(Obsv)
n = A.shape[0]  # Number of states

if rank_O == n:
    print("The system is observable.")
else:
    print("The system is not observable.")

print("Observability matrix:\n", Obsv)
print("Rank of the observability matrix:", rank_O)


The system is observable.
Observability matrix:
 [[ 1  0  1]
 [ 1  3  3]
 [ 3 10 12]]
Rank of the observability matrix: 3


In [ ]:
# Rank of controllability matrix

A = np.array([[0, 1, 0], [0, 1, 1], [1, 2, 3]])
B = np.array([[1], [0], [0]])

# Compute the controllability matrix
Ctrb = np.hstack([B, A @ B, A @ A @ B])

# Compute the rank
rank_C = np.linalg.matrix_rank(Ctrb)
n = A.shape[0]  # Number of states

if rank_C == n:
    print("The system is controllable.")
else:
    print("The system is not controllable.")

print("Controllability matrix:\n", Ctrb)
print("Rank of the controllability matrix:", rank_C)


The system is controllable.
Controllability matrix:
 [[1 0 0]
 [0 0 1]
 [0 1 3]]
Rank of the controllability matrix: 3


In [ ]:
# Task 4.2: Finding a Feedback Control Law
A2 = np.array([[1, 1], [1, 2]])
B2 = np.array([[1], [0]])

In [ ]:
# Solve the continuous-time algebraic Riccati equation
Q = np.eye(2)  # State cost matrix
R = np.eye(1)  # Control cost matrix

P = solve_continuous_are(A2, B2, Q, R)

In [ ]:
# Compute the optimal feedback gain K
K = np.linalg.inv(R) @ B2.T @ P

print("Feedback gain K:", K)
print("Closed-loop eigenvalues:", eigenvalues)

# Check stability
if np.all(np.real(eigenvalues) < 0):
    print("The system is stable.")
else:
    print("The system is NOT stable.")

Feedback gain K: [[ 6.59151493 14.6325196 ]]
Closed-loop eigenvalues: [-2.6762432  -0.91527173]
The system is stable.


In [ ]:
import numpy as np
from scipy.linalg import solve_continuous_are

# Define A and B matrices
A = np.array([[1, 1], [1, 2]])
B = np.array([[1], [0]])

# Define cost matrices for Riccati equation
Q = np.eye(2)
R = np.eye(1)

# Solve Riccati equation
P = solve_continuous_are(A, B, Q, R)

# Compute the optimal feedback gain
K = np.linalg.inv(R) @ B.T @ P

# Compute the closed-loop matrix
A_cl = A - B @ K

# Compute eigenvalues
eigenvalues = np.linalg.eigvals(A_cl)

print("Optimal feedback gain K:", K)
print("Closed-loop eigenvalues:", eigenvalues)

# Check stability
if np.all(np.real(eigenvalues) < 0):
    print("The system is stable.")
else:
    print("The system is NOT stable.")


Optimal feedback gain K: [[ 6.59151493 14.6325196 ]]
Closed-loop eigenvalues: [-2.6762432  -0.91527173]
The system is stable.
